data_structures_final/Controllers/StackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace data_structures_final.Controllers
{
    public class StackController : Controller
    {
        static Stack<string> myStack = new Stack<string>();
        
        

        // GET: Stack
        public ActionResult Index()
        {
            ViewBag.MyStack = myStack;
            return View();
        }

        //Adding one to the stack
        public ActionResult AddOne()
        {
            myStack.Push("<p hidden>" + "New Entry " + (myStack.Count + 1) + "</p>");
            ViewBag.MyStack = myStack;
            return View("Index");
        }

        //Adding 2000 using a for loop to push to the stack
        public ActionResult AddHugeList()
        {
            myStack.Clear();
            for (int i = 0; i < 2000; i++)
            {
                myStack.Push("<p hidden>" + "New Entry " + (myStack.Count + 1) + "</p>");
            }
            ViewBag.MyStack = myStack;
            return View("Index");
        }

        //Displaying the stack
        public ActionResult Display()
        {
            foreach (string item in myStack)
            {
                ViewBag.MyStack += item.Replace("<p hidden>", "<p>");
                ViewBag.MyStack += item.Replace("<button hidden>", "<>");
            }
            return View("Index");
        }

        //Delete from the stack
        public ActionResult Delete()
        {
            if (myStack.Count > 0)
            {
                myStack.Pop();
                ViewBag.MyStack = myStack;
            }
            else
            {
                ViewBag.MyStack = " <p>Add Items to the Stack!</p>";
            }
        

        return View("Index");
        }

        //Clear from the Stack
        public ActionResult Clear()
        {
            myStack.Clear();
            ViewBag.MyStack = "<p>Add Items to the Stack!</p>";
            return View("Index");
        }

        //Search from the Stack
        public ActionResult Search()
        {
            if (myStack.Count > 0)
            {
                string FindMe = "New Entry 15";
                string Found = "Found";
                string NotFound = "Not Found";
                ViewBag.Time = NotFound;
                System.Diagnostics.Stopwatch sw = new System.Diagnostics.Stopwatch();

                sw.Start();
                foreach(string item in myStack)
                {
                    if (item.Contains(FindMe))
                    {
                        sw.Stop();
                        TimeSpan ts = sw.Elapsed;
                        ViewBag.StopWatch = ts;
                        ViewBag.Time = Found;
                    }
                    else
                    {
                        TimeSpan ts = sw.Elapsed;
                        ViewBag.StopWatch = ts;
                    }

                } 
                sw.Stop();

            }
            return View("Search");
        }
    }
}

data_structures_final/Views/Stack/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
</head>
<body>
    <div>
        <ul>
            <li>
                <a href="@Url.Action("AddOne", "Stack")"
                   class="w3-bar-item w3-button">Add One Item to Stack</a>
            </li>
            <li>
                <a href="@Url.Action("AddHugeList", "Stack")"
                   class="w3-bar-item w3-button">Add Huge List of Items to Stack</a>
            </li>
            <li>
                <a href="@Url.Action("Display", "Stack")"
                   class="w3-bar-item w3-button">Display Stack</a>
            </li>
            <li>
                <a href="@Url.Action("Delete", "Stack")"
                   class="w3-bar-item w3-button">Delete From Stack</a>
            </li>
            <li>
                <a href="@Url.Action("Clear", "Stack")"
                   class="w3-bar-item w3-button">Clear Stack</a>
            </li>
            <li>
                <a href="@Url.Action("Search", "Stack")"
                   class="w3-bar-item w3-button">Search Stack</a>
            </li>
            <li>
                <a href="@Url.Action("Index", "Home")"
                   class="w3-bar-item w3-button">Return to Main Menu</a>
            </li>
        </ul>
    </div>
    @if (ViewBag.MyStack != null)
    {
        foreach (var sData in ViewBag.MyStack)
        {
            @Html.Raw(sData)
        }
    }
    else if(ViewBag.Time == "Found")
    {
    <p>@ViewBag.Time + in + @ViewBag.StopWatch</p>
    }


    else
    {
        <p>Add Items to the Stack!</p>
    }

</body>
</html> 

data_structures_final/Views/Stack/Search.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Search</title>
</head>
<body>
    <div>
        <p> @ViewBag.Time</p>
        <p>@ViewBag.StopWatch</p>
      
    </div>
</body>
</html>